### ISSUE TITLE
unable to do the bootstrap

### ISSUE THREAD

**Issue by fengyuchengdu** [emvolz-phylodynamics/mlesky#10]
1. par <- parboot(fit)
 throwing "Error in ape::node.depth.edgelength(apephylo) : 
  NA/NaN/Inf in foreign function call (arg 4)"

2. in the example, bootstrap was done without specifying model, what is the default for mlskygrid()? will this make difference when doing bootstrap?

many thanks !!!

**Comment by xavierdidelot** [comment]
1. Does this error happen when you run the vignette `simulation.Rmd`? If yes then there is something strange on your side as this works fine on mine. If no then there is something strange with your input.
2. The default model in `mlskygrid` is the skykappa model. `parboot` always uses the same model as was used in the first parameter `fit`
