### ISSUE TITLE
can not install mlesky

### ISSUE THREAD

**Issue by liamxg** [emvolz-phylodynamics/mlesky#5]
devtools::install_github('emvolz-phylodynamics/mlesky')
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2022-05-16 05:27:53 UTC

  
>

**Comment by xavierdidelot** [comment]
This is a problem specific to your environment rather than mlesky. I think it can be solved by using the following command before you try to install again.
`Sys.unsetenv("GITHUB_PAT")`

**Comment by liamxg** [comment]
thanks for your kindly help, very appreciated for this.
