### ISSUE TITLE
what is res meaning here, thanks.

### ISSUE THREAD

**Issue by liamxg** [emvolz-phylodynamics/mlesky#6]
res=optim_res_aic(treeMRSA,ncpu=6)
print(res)

**Comment by xavierdidelot** [comment]
res is the optimal resolution, ie the optimal number of points to describe the effective population size function in discrete time.

**Comment by liamxg** [comment]
thanks for your help, like time intervals right?

**Comment by xavierdidelot** [comment]
Yes it's the number of time intervals.

**Comment by liamxg** [comment]
thanks for your kindly help, but how this model can be use in my study?

**Comment by xavierdidelot** [comment]
See the preprint at https://www.biorxiv.org/content/10.1101/2021.01.18.427056v2.full

**Comment by liamxg** [comment]
thanks.
