### ISSUE TITLE
what is tau meaning here, thanks.

### ISSUE THREAD

**Issue by liamxg** [emvolz-phylodynamics/mlesky#8]
tau =  18.4332061932401

**Comment by liamxg** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/46078579/170871136-40b10560-7374-45cc-a50b-6b13d9e8989f.png">
is this normal or not?

**Comment by xavierdidelot** [comment]
Maybe, it depends what your data looks like. It would be better to plot the effective population size on a log scale, and also to look at the growth rate.

**Comment by liamxg** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/46078579/171081172-17fe536b-64c2-4c48-83bb-233bb72f93f9.png">

**Comment by liamxg** [comment]
plot(fit,logy=TRUE) like this, right?

**Comment by liamxg** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/46078579/171081927-5174c699-9a90-4a20-9b34-60b2ecaf33e9.png">

**Comment by liamxg** [comment]
could you please tell me how to look at the growth rate, thanks.

**Comment by xavierdidelot** [comment]
Yes `logy=TRUE` is indeed what you need to use to have the y-axis on a log-scale.
To plot the growth rate you need to use `growth=TRUE`
It looks like your analysis is completely uninformative.

**Comment by liamxg** [comment]
thanks for your help,  like the following?
> plot(fit,logy=TRUE,growth=TRUE)
Warning message:
In xy.coords(x, y, xlabel, ylabel, log) :
  17 y values <= 0 omitted from logarithmic plot

**Comment by liamxg** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/46078579/171192130-c5add27a-2e10-45c1-ae36-b745a8180f62.png">

**Comment by xavierdidelot** [comment]
`plot(fit,logy=FALSE,growth=TRUE)` would be better, for the growth rate you usually don't want the logged y axis.

**Comment by liamxg** [comment]
thanks. like this?
<img width="421" alt="image" src="https://user-images.githubusercontent.com/46078579/171193139-9165e425-2829-4078-9f35-0cf8fc38f4e0.png">

**Comment by liamxg** [comment]
no 95% interval

**Comment by xavierdidelot** [comment]
Yes but this looks hard to believe. You should check your data is used correctly. Email me if you need help.

**Comment by liamxg** [comment]
thanks, is this your email (xavier.didelot@gmail.com), thanks.

**Comment by xavierdidelot** [comment]
Yes it is.

**Comment by liamxg** [comment]
thanks.
