### ISSUE TITLE
a bug about vmmin

### ISSUE THREAD

**Issue by Naclist** [emvolz-phylodynamics/mlesky#9]
I used your staphy examples and get an error as below when try to run 'fit = mlskygrid(treeMRSA)':

Error in optim(par = theta0, fn = of, method = "BFGS", control = list(trace = ifelse(quiet,  : 
initial value in 'vmmin' is not finite

I dont know if it is like a systematic error because when I use another device, the example code run well...

**Comment by xavierdidelot** [comment]
sorry I could not reproduce this error on my side...

**Comment by Naclist** [comment]
> sorry I could not reproduce this error on my side...

That's OK, I can handle the newick of my own...I am just curious

**Comment by Naclist** [comment]
> > sorry I could not reproduce this error on my side...
> 
> That's OK, I can handle the newick of my own...I am just curious

Update, I did not realize my tree was a polytomy
